---
# Copyright 2017, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Gather facts
  hosts: keystone_all
  gather_facts: "{{ gather_facts | default(true) }}"
  pre_tasks:
    - include: "common-tasks/maas_excluded_regex.yml"

  tasks:
    - name: Copy over pip constraints
      copy:
        src: "files/pip-constraints.txt"
        dest: "/tmp/pip-constraints.txt"
      delegate_to: "{{ physical_host | default(ansible_host) }}"

  post_tasks:
    - name: Install keystone pip packages to venv
      pip:
        name: "{{ maas_openstack_keystone_pip_packages | join(' ') }}"
        state: "{{ maas_pip_package_state }}"
        extra_args: >-
          --isolated
          --constraint /tmp/pip-constraints.txt
          {{ pip_install_options | default('') }}
        virtualenv: "{{ maas_venv }}"
      register: install_pip_packages
      until: install_pip_packages|success
      retries: 5
      delay: 2
      delegate_to: "{{ physical_host | default(ansible_host) }}"

  vars_files:
    - vars/main.yml
    - vars/maas-openstack.yml
  tags:
    - maas-openstack-keystone

- name: Install checks for openstack keystone
  hosts: keystone_all
  gather_facts: false
  pre_tasks:
    - name: Create keystone user for monitoring
      keystone:
        command: "ensure_user"
        endpoint: "{{ keystone_service_adminurl }}"
        login_user: "{{ keystone_admin_user_name }}"
        login_password: "{{ keystone_auth_admin_password }}"
        login_project_name: "{{ keystone_admin_tenant_name }}"
        user_name: "{{ maas_keystone_user }}"
        tenant_name: "{{ keystone_admin_tenant_name }}"
        password: "{{ maas_keystone_password }}"
        insecure: "{{ keystone_service_adminuri_insecure }}"
      when:
        - keystone_service_adminurl is defined
        - keystone_admin_user_name is defined
        - keystone_auth_admin_password is defined
        - keystone_admin_tenant_name is defined
        - keystone_service_adminuri_insecure is defined
        - inventory_hostname in groups['keystone_all'][0]

    - name: Add monitoring keystone user to admin role
      keystone:
        command: "ensure_user_role"
        endpoint: "{{ keystone_service_adminurl }}"
        login_user: "{{ keystone_admin_user_name }}"
        login_password: "{{ keystone_auth_admin_password }}"
        login_project_name: "{{ keystone_admin_tenant_name }}"
        user_name: "{{ maas_keystone_user }}"
        tenant_name: "{{ keystone_admin_tenant_name }}"
        role_name: "admin"
        insecure: "{{ keystone_service_adminuri_insecure }}"
      when:
        - keystone_service_adminurl is defined
        - keystone_admin_user_name is defined
        - keystone_auth_admin_password is defined
        - keystone_admin_tenant_name is defined
        - keystone_service_adminuri_insecure is defined
        - inventory_hostname in groups['keystone_all'][0]

  tasks:
    - name: Install keystone api checks
      template:
        src: "templates/keystone_api_local_check.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/keystone_api_local_check--{{ inventory_hostname }}.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      delegate_to: "{{ physical_host | default(ansible_host) }}"
      notify:
        - Restart rax-maas

    - name: Install keystone lb checks
      template:
        src: "templates/lb_api_check_keystone.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/lb_api_check_keystone.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      delegate_to: "{{ physical_host | default(ansible_host) }}"
      when:
        - maas_remote_check | bool
      notify:
        - Restart rax-maas

  handlers:
    - include: handlers/main.yml
  vars_files:
    - vars/main.yml
    - vars/maas-openstack.yml
  tags:
    - maas-openstack-keystone
