# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      os_cloud:
        description: 'used for the openstackclient --os_cloud argument'
        default: 'phobos'
        required: true
      flavor:
        description: 'flavor used for aio build'
        default: 'vm-osa-aio'
        required: true
      image:
        description: 'image used for aio build'
        default: 'Ubuntu 18.04'
        required: true
      network:
        description: 'neutron network used for aio build'
        default: 'ironic'
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  create_vm:
    runs-on: self-hosted
    steps:
    - name: Run create command
      run: |
        echo "openstack --os-cloud ${{ github.event.inputs.os_cloud }} --flavor ${{ github.event.inputs.flavor }} --image \"${{ github.event.inputs.image }}\" --network ${{ github.event.inputs.network }} rpc-maas-${{ github.run_id }}-${{ github.run_number }}"
        env > env_test.txt
